name: droid-contained
services:
    docker-android:
        ports:
            - 6080:6080
        environment:
            - EMULATOR_DEVICE=Samsung Galaxy S10
            - WEB_VNC=true
        devices:
            - /dev/kvm
        image: budtmo/docker-android:emulator_13.0